/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package reto.sophos.interactions;

import java.awt.Robot;
import java.awt.AWTException;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;

public class RobotJava {
    Robot robot = new Robot();

    public RobotJava() throws AWTException {

        robot.keyPress(KeyEvent.VK_ENTER); //press enter key
        robot.keyRelease(KeyEvent.VK_ENTER); //release enter key
        robot.delay(1000);
        robot.keyPress(KeyEvent.VK_ENTER); //press enter key
        robot.keyRelease(KeyEvent.VK_ENTER); //release enter key
        robot.delay(1000);
    }
  
}
