/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package reto.sophos.exceptions;

public class CarroCompras extends AssertionError {
    private static final long serialVersionUID = 1L;
    public static final String PRODUCTO_EN_EL_CARRITO = "Fallo adicionando el producto al carrito";

    public CarroCompras(String mensaje, Throwable error) {
        super(mensaje, error);
    }
}
